services:
  broker-service:
    build:
      context: ./broker
      dockerfile: ./broker.Dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1


  authentication-service:
    build:
      context: ./auth
      dockerfile: ./auth.Dockerfile
    restart: always
    ports:
      - "8081:80"
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - auth/.env



  postgres:
    image: "postgres:latest"
    ports:
      - "5433:543"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - auth/.env
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
