services:
  broker-service:
    build:
      context: ./broker
      dockerfile: ./broker.Dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1
