services:
  broker-service:
    build:
      context: ./broker
      dockerfile: ./broker.Dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1

  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - auth/.env
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
