apiVersion: apps/v1
kind: Deployment
metadata:
  name: listener-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: listener-service
  template:
    metadata:
      labels:
        app: listener-service
    spec:
      containers:
        - name: listener-service
          image: "arshio12/listener-service:1.0.0"
          envFrom:
            - configMapRef:
                name: listener-env
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: listener-service
spec:
  selector:
    app: listener-service
  ports:
    - port: 8080
      targetPort: 8080
      name: main-port
      protocol: TCP

