apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logger-service
  template:
    metadata:
      labels:
        app: logger-service
    spec:
      containers:
        - name: logger-service
          image: "arshio12/logger-service:1.0.0"
          envFrom:
            - configMapRef:
                name: logger-env
          ports:
            - containerPort: 8080
            - containerPort: 5001
            - containerPort: 50001